version: "3.9"
services:
  mofu:
    build: .
    environment:
      TELEGRAM_BOT_TOKEN: bot-token
      CONTROL_ROOM_ID: control-room
      WARNING_ROOM_ID: warning-room
      BROADCAST_ROOM_ID: broadcast-room
      TWITTER_API_TOKEN: twitter-token
      DEV: 1
      DATABASE: postgres://database/postgres
    volumes:
      - ./data:/app/data/
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: on-failure
  database:
    image: "postgres:15.1"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  backup:
    image: eeshugerman/postgres-backup-s3:13
    environment:
      SCHEDULE: '@weekly'     # optional
      BACKUP_KEEP_DAYS: 7     # optional
      PASSPHRASE: passphrase  # optional
      S3_REGION: region
      S3_ACCESS_KEY_ID: key
      S3_SECRET_ACCESS_KEY: secret
      S3_BUCKET: my-bucket
      S3_PREFIX: backup
      POSTGRES_HOST: postgres
      POSTGRES_DATABASE: dbname
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password