// Code generated by ent, DO NOT EDIT.

package ent

import (
	"mofu/ent/history"
	"mofu/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	historyFields := schema.History{}.Fields()
	_ = historyFields
	// historyDescCreateAt is the schema descriptor for create_at field.
	historyDescCreateAt := historyFields[2].Descriptor()
	// history.DefaultCreateAt holds the default value on creation for the create_at field.
	history.DefaultCreateAt = historyDescCreateAt.Default.(func() time.Time)
	// historyDescLastUpdate is the schema descriptor for last_update field.
	historyDescLastUpdate := historyFields[3].Descriptor()
	// history.DefaultLastUpdate holds the default value on creation for the last_update field.
	history.DefaultLastUpdate = historyDescLastUpdate.Default.(func() time.Time)
	// history.UpdateDefaultLastUpdate holds the default value on update for the last_update field.
	history.UpdateDefaultLastUpdate = historyDescLastUpdate.UpdateDefault.(func() time.Time)
	// historyDescMentionedCount is the schema descriptor for mentioned_count field.
	historyDescMentionedCount := historyFields[6].Descriptor()
	// history.DefaultMentionedCount holds the default value on creation for the mentioned_count field.
	history.DefaultMentionedCount = historyDescMentionedCount.Default.(int)
}
