// Code generated by ent, DO NOT EDIT.

package author

const (
	// Label holds the string label denoting the author type in the database.
	Label = "author"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldUserName holds the string denoting the user_name field in the database.
	FieldUserName = "user_name"
	// Table holds the table name of the author in the database.
	Table = "authors"
)

// Columns holds all SQL columns for author fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldUserName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
